version: '3.8'
services:
  mongo:
    image: 'mongo'
  nginx:
    depends_on: 
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:80'
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '4000:3000'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - MONGO_HOST=mongo
    ports:
      - '8080:8080'
    
            
        
    
        

    